// products.js
export const products = [
  {
    id: 1,
    category: "Spot Light",
    name: "APL1081",
    image: "/products/magnetic1.jpg",
    link: "/products/magnetic1", // This will be your product page
  },
  {
    id: 2,
    category: "Spot Light",
    name: "DLRC1001",
    image: "/products/linear1.jpg",
    link: "/products/linear1",
  },
  {
    id: 3,
    category: "Spot Light",
    name: "DLRC1101",
    image: "/products/downlight1.jpg",
    link: "/products/downlight1",
  },
  {
    id: 4,
    category: "SpotLight",
    name: "DLRC1381",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 5,
    category: "Spot Light",
    name: "DLRC1441",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 6,
    category: "Spot Light",
    name: "DLRC1541",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 7,
    category: "Spot Light",
    name: "DLRC1381",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 8,
    category: "Spot Light",
    name: "DLRC1681",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
     {
    id: 9,
    category: "Spot Light",
    name: "DLRC1761",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
     {
    id: 10,
    category: "Spot Light",
    name: "DLRC1801",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
     {
    id: 11,
    category: "Spot Light",
    name: "DLRC1961",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
     {
    id: 12,
    category: "Spot Light",
    name: "SLRC2001",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
     {
    id: 13,
    category: "Spot Light",
    name: "SLRC2081",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 14,
    category: "Spot Light",
    name: "SLRC2101",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 15,
    category: "Spot Light",
    name: "SLRC212",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 16,
    category: "Spot Light",
    name: "SLRC2181",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 17,
    category: "Spot Light",
    name: "SLRC2081",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 18,
    category: "Spot Light",
    name: "SLRC2701",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 19,
    category: "Spot Light",
    name: "SLRC3001",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 20,
    category: "Spot Light",
    name: "SLRC3581",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 21,
    category: "Spot Light",
    name: "SLRC2081",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 22,
    category: "Spot Light",
    name: "SLRC4061",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 23,
    category: "Spot Light",
    name: "SLRC4401",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 24,
    category: "Spot Light",
    name: "SLRC4581",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 25,
    category: "Spot Light",
    name: "SLRC4661",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 26,
    category: "Spot Light",
    name: "SLRC4761",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 27,
    category: "Spot Light",
    name: "SLRC4821",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 28,
    category: "Spot Light",
    name: "SLRC4861",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 29,
    category: "Spot Light",
    name: "SLRC4881",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 30,
    category: "Spot Light",
    name: "SLRC4961",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 31,
    category: "Spot Light",
    name: "SLRC4981",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 32,
    category: "Spot Light",
    name: "SLRC5021",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 33,
    category: "Spot Light",
    name: "SLRC5021",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 34,
    category: "Spot Light",
    name: "SLRC5021",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 35,
    category: "Spot Light",
    name: "SLRC5161",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 36,
    category: "Spot Light",
    name: "SLRC5481",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 36,
    category: "Spot Light",
    name: "SLRC5581",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 37,
    category: "Spot Light",
    name: "SLRC5661",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 38,
    category: "Spot Light",
    name: "SLRC5741",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 39,
    category: "Spot Light",
    name: "SLRC5761",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 40,
    category: "Spot Light",
    name: "SLRC5781",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 41,
    category: "Spot Light",
    name: "SLRC5881",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 42,
    category: "Spot Light",
    name: "SLRC5981",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 43,
    category: "Spot Light",
    name: "SLRC6301",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 44,
    category: "Spot Light",
    name: "SLRC6421",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 45,
    category: "Spot Light",
    name: "SLRC6501",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 46,
    category: "Spot Light",
    name: "SLRC6661",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 47,
    category: "Spot Light",
    name: "SLRC6681",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 48,
    category: "Spot Light",
    name: "SLRC6701",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 49,
    category: "Spot Light",
    name: "SLRC6761",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 50,
    category: "Spot Light",
    name: "SLRC6861",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 51,
    category: "Spot Light",
    name: "SLRC6881",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 51,
    category: "Spot Light",
    name: "SLRC6901",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 53,
    category: "Spot Light",
    name: "SLRC6941",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
   {
    id: 54,
    category: "Spot Light",
    name: "SMS1841",
    image: "/products/mirror1.jpg",
    link: "/products/mirror1",
  },
  {
    id: 55,
    category: "Mirror Light",
    name: "MIR2031",
    image: "/MIR203I.jpg",
    link: "/products/Mirror1",
  },
   {
    id: 56,
    category: "Mirror Light",
    name: "WLS1400",
    image: "/MIRWLS1400.jpg",
    link: "/products/Mirror1",
  },
   {
    id: 57,
    category: "Mirror Light",
    name: "WLS1800",
    image: "/MIRWLS180O.jpg",
    link: "/products/Mirror1",
  },
];